import { VerticalBox, Button, TextEdit, ScrollView, TextEdit} from "std-widgets.slint";

struct WeatherForTime {
    time: string,
    time_condition_icon: image,
    temperature: string
}

export component MainWindow inherits Window {
    title: "";
    icon: @image-url("");
    no-frame: true;
    background: transparent;
    resize-border-width: 0;
    width: 300px;
    height: 560px;
    in-out property <string> country;
    in-out property <string> city;
    in-out property <string> temperature;
    in-out property <string> condition;
    in-out property <string> date;
    in-out property <string> time;
    in-out property <image> image;
    in-out property <string> text_input_placeholder;
    in-out property <color> text-color;
    in-out property <color> first_gradient_color;
    in-out property <color> second_gradient_color;
    in property <string> humidity;
    in property <string> wind_kph;
    in property <string> feels_like_c;

    in property <[WeatherForTime]> my_vector_data: [];

    callback mouse_move(length, length);
    callback close_window();
    callback reload_window;
    callback window_minimize();
    callback city_submitted(string);
    callback set_inputtext_text(string);


    function test() -> string{
        city_input.text = "";
        city_input.clear-focus();
        return "allgood";
    }

    TouchArea {
        clicked => {
            city_input.clear-focus();
        }
        moved => {
            root.mouse_move(self.mouse-x - self.pressed-x, self.mouse-y - self.pressed-y);
        }
    }


    VerticalLayout {
        Rectangle {
            width: 100%;
            height: 100%;
            background: @linear-gradient(180deg, first_gradient_color 0%, second_gradient_color 100%);
            animate background { duration: 800ms; easing: ease-in-out;}
            border-radius: 8px;

            HorizontalLayout {
                x: parent.width - 65px;
                y: 5px;

                Rectangle {
                    width: 20px;
                    height: 20px;
                    Button {
                        width: 20px;
                        height: 20px;
                        clicked => {
                            root.window-minimize();
                        }
                    }
                    Image {
                        opacity: 0.5;
                        width: 21px;
                        height: 21px;
                        source: @image-url("icons/green.png");
                    }
                }


                Rectangle {

                    width: 20px;
                    height: 20px;
                    Button {
                        width: 20px;
                        height: 20px;
                        clicked => {
                            root.reload_window();
                        }
                    }
                    Image {
                        opacity: 0.5;
                        width: 18px;
                        height: 18px;
                        source: @image-url("icons/blue.png");
                    }
                }
                Rectangle {
                    width: 20px;
                    height: 20px;
                    Button {
                        width: 20px;
                        height: 20px;
                        clicked => {
                            root.close_window();
                        }
                    }
                    Image {
                        opacity: 0.5;
                        width: 21px;
                        height: 21px;
                        source: @image-url("icons/red.png");
                    }
                }
            }

                city_input := TextInput {
                    x: 10px;
                    y: 10px;
                    width: parent.width * 0.7;
                    height: 40px;
                    in-out property <string> name : city_input.text;
                    // text: "⚲ " + country + ", " + city;
                    font-size: 16px;
                    font-weight: 800;
                    font-family: "Segoe UI";
                    color: text-color;
                    wrap: word-wrap;
                    horizontal-alignment: left;


                    if(city_input.has-focus == true): Rectangle {

                        height: 20px;
                        x: 0px;
                        y: 0px;
                        background: transparent;
                    }
                    if(city_input.has-focus == false): Rectangle {
                        height: 20px;
                        x: 0px;
                        y: 0px;
                        border-radius: 8px;
                        border-color: second_gradient_color;
                        border-width: 2px;
                        Text {
                            x: 0px;
                            y: 0px;
                            width: root.width * 0.7;
                            text: "⚲ " + country + ", " + city;
                            font-size: 16px;
                            font-weight: 800;
                            font-family: "Segoe UI";
                            color: text-color;
                            horizontal-alignment: left;
                            wrap: word-wrap;
                        }
                    }


                    accepted() => {
                        city_input.clear-focus();
                        root.city_submitted(name);
                        test();
                    }

                }

            // input_field := TouchArea {
            //         x: 10px;
            //         y: 10px;
            //         width: parent.width / 2;
            //         height: 40px;
            //     city_input := TextInput {
            //         read-only: true;
            //     }
            //     clicked => {
            //         city_input.focus();
            //         city_input.read-only = false;
            //     }
            // }



            VerticalLayout {
                y: 70px;
                width: 100%;
                height: 40%;
                Text {
                    width: parent.width;
                    font-family: "Segoe UI";
                    text: date + "\n" + time;
                    font-size: 18px;
                    font-weight: 700;
                    font-italic: true;
                    color: text-color;
                    horizontal-alignment: center;
                    wrap: word-wrap;
                }

                Text {
                    width: parent.width;
                    font-family: "Segoe UI";
                    text: temperature + "°C";
                    font-size: 70px;
                    font-weight: 800;
                    color: text-color;
                    horizontal-alignment: center;
                    wrap: word-wrap;
                }

                Image {
                    source: image;
                    width: 100px;
                    height: 100px;
                    horizontal-alignment: center;
                    x: root.width*0.5-50px;
                }

                Text {
                    x: 0;
                    width: parent.width;
                    font-family: "Segoe UI";
                    text: condition;
                    font-size: 20px;
                    font-weight: 700;
                    color: text-color;
                    horizontal-alignment: center;
                    wrap: word-wrap;
                }

                spacing: 10px;
                HorizontalLayout {

                    spacing: 30px;
                    width: root.width;
                    alignment: center;
                    property <length> size: 55px;
                    property <string> font-family: "Segoe UI";
                    property <length> font-size: 12px;
                    property <int> font-weight: 700;
                    property <color> font-color: text-color;
                    property <length> text_y: 62px;
                    Image {
                        width: size;
                        height: size;
                        source: @image-url("icons/raindrops.png");
                        Text {
                            horizontal-alignment: center;
                            y: text_y;
                            text: "HUMIDITY\n" + humidity + "%";
                            font-family: font-family;
                            font-size: font-size;
                            font-weight: font-weight;
                            color: font-color;
                        }
                    }
                    Image {
                        width: size;
                        height: size;
                        source: @image-url("icons/windy.png");
                        Text {
                            horizontal-alignment: center;
                            y: text_y;
                            text: "WIND\n" + wind_kph + " km/h";
                            font-family: font-family;
                            font-size: font-size;
                            font-weight: font-weight;
                            color: font-color;
                        }
                    }
                    Image {
                        width: size;
                        height: size;
                        source: @image-url("icons/thermometer.png");
                        Text {
                            horizontal-alignment: center;
                            y: text_y;
                            text: "FEELS LIKE\n" + feels_like_c + "°C";
                            font-family: font-family;
                            font-size: font-size;
                            font-weight: font-weight;
                            color: font-color;
                        }
                    }
                }
            }

            Rectangle {
                background: rgba(240, 240, 240, 0.2);
                y: root.height - 78px;
                width: 280px;
                height: 70px;
                border-radius: 8px;

                HorizontalLayout {
                    padding: 10px;
                    spacing: 10px;
                    width: 100%;
                    height: 100px;
                    y: parent.height -75px;
                    for model[index] in my_vector_data : HorizontalLayout {
                        spacing: -25px;

                        Image {
                            source: model.time_condition_icon;
                            width: 60px;
                            height: 60px;
                        }
                        Rectangle {
                            y: parent.height - 67px;
                            width: 46px;
                            height: 46px;
                            border-radius: 8px;
                            background: first_gradient_color.with-alpha(0.6);
                            Text {
                                text: model.time + "\n" + model.temperature + "°C";
                                font-family: "Segoe UI";
                                color: text-color;
                                font-weight: 700;
                                font-size: 14px;
                            }
                        }
                    }
                }


            }
        }
    }
}
